"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.toMarkdown = toMarkdown;
exports.practiceTarget = practiceTarget;
exports.toSelfContainedHtml = toSelfContainedHtml;
exports.toCollectionIndexHtml = toCollectionIndexHtml;
const annotations_1 = require("./annotations");
const customize_1 = require("./customize");
const ScreenshotStore_1 = require("./ScreenshotStore");
const schema_1 = require("./schema");
function toMarkdown(guide, opts = {}) {
    const lines = [`# ${guide.title}`, ''];
    if (guide.intent)
        lines.push(guide.intent, '');
    if (guide.estimatedMinutes)
        lines.push(`**Time:** about ${guide.estimatedMinutes} minutes`, '');
    if (guide.audience)
        lines.push(`**Audience:** ${guide.audience}`, '');
    if (guide.prerequisites.length) {
        lines.push('## Before you start', '');
        for (const item of guide.prerequisites)
            lines.push(`- ${item}`);
        lines.push('');
    }
    const grouped = (0, schema_1.hasChapters)(guide.steps);
    if (!grouped)
        lines.push('## Steps', '');
    const byId = new Map(guide.steps.map((step, i) => [step.id, i + 1]));
    guide.steps.forEach((step, index) => {
        // A chapter heading is emitted at the first step that carries a new title.
        if (grouped && step.chapter?.trim() && guide.steps[index - 1]?.chapter?.trim() !== step.chapter.trim()) {
            lines.push(`## ${step.chapter.trim()}`, '');
        }
        lines.push(`### ${index + 1}. ${step.title}`, '');
        if (step.body)
            lines.push(step.body, '');
        if (step.why)
            lines.push(`> **Why:** ${step.why}`, '');
        // Relative to the exported file; the writer copies the images into ./steps/ alongside it.
        if (step.screenshot)
            lines.push(`![${escapeAlt(step.title)}](steps/${basename(step.screenshot)})`, '');
        if (step.verify)
            lines.push(`*Check:* ${describeVerify(step)}`, '');
        /**
         * Markdown cannot offer a button, so a branch becomes a numbered jump the reader follows by
         * eye. The step number is what they can act on; the id is not shown, because it is an
         * internal handle and would read as noise.
         */
        if (step.branches?.length) {
            lines.push('*What happens next depends on your answer:*', '');
            for (const branch of step.branches) {
                const target = byId.get(branch.goto);
                lines.push(`- ${branch.label} → ${target ? `go to step ${target}` : 'end of guide'}`);
            }
            lines.push('');
        }
        if (step.outputs?.length) {
            lines.push('*This step produces a value you will need later:*', '');
            for (const output of step.outputs) {
                lines.push(`- **${output.name}** → \`${output.target}\`${output.sensitive ? ' _(keep this secret)_' : ''}`);
            }
            lines.push('');
        }
    });
    lines.push('---', '');
    /**
     * Markdown carries no styling, so branding degrades to the one thing it can express: the
     * organisation's name, and whether the attribution line is kept. The logo and colours are
     * simply absent rather than approximated.
     */
    const brand = guide.branding?.enabled ? guide.branding : null;
    if (brand?.organisation)
        lines.push(`${brand.organisation}`, '');
    if (brand?.showAttribution !== false) {
        lines.push(`Generated by 1ShowcaseTool on ${formatDate(guide.generatedAt)}.`);
    }
    else {
        lines.push(`Generated on ${formatDate(guide.generatedAt)}.`);
    }
    if (opts.watermark)
        lines.push('', `_${opts.watermark}_`);
    /**
     * Markdown has no way to overlay a mark on an image, so the writer composites them into the
     * copies in ./steps/ instead. Those copies are the only place the marks are pixels — the
     * stored screenshot is untouched, and the HTML and video exports still draw them as data.
     */
    if (guide.steps.some((step) => step.annotations.length)) {
        lines.push('', 'The screenshots in ./steps/ have their arrows and highlights drawn in.');
    }
    // The manifest travels with the guide so a teammate can audit what was masked (§7.2).
    if (guide.redaction.rules.length) {
        lines.push('', `Redaction applied: ${guide.redaction.rules.join(', ')}.`);
    }
    if (guide.redaction.placeholders.length) {
        lines.push('', `Placeholders you must substitute: ${guide.redaction.placeholders.join(', ')}.`);
    }
    return lines.join('\n');
}
/**
 * The variables runtime, inlined into the export.
 *
 * **Nothing is persisted, and that is the whole design.** A placeholder often names a client
 * secret or an API key, and these are the *reader's* own values — the same class of data
 * §7.6 refuses to let the extension put in `chrome.storage`. So they live in the DOM for the
 * life of the tab and nowhere else: no localStorage, no sessionStorage, no cookie, no fetch.
 * Closing the tab is the delete button, and the panel says so in those words.
 */
const VARIABLES_SCRIPT = `<script>
(function () {
  var inputs = document.querySelectorAll('input[data-fills]');
  for (var i = 0; i < inputs.length; i++) {
    inputs[i].addEventListener('input', function (event) {
      var name = event.target.getAttribute('data-fills');
      var value = event.target.value;
      var marks = document.querySelectorAll('.gt-var[data-var="' + CSS.escape(name) + '"]');
      for (var j = 0; j < marks.length; j++) {
        marks[j].textContent = value || name;
        marks[j].classList.toggle('is-filled', !!value);
      }
    });
  }
})();
</script>`;
/**
 * Where a practice click must land, as fractions of the screenshot.
 *
 * Derived from the step's annotations rather than stored separately: the box *is* the target
 * rect the recorder measured, and an arrow's tip abuts its edge. A step with neither has no
 * measured target and practice mode falls back to a Continue button — the same honesty rule
 * deriveAnnotations follows: never invent a place to click.
 */
function practiceTarget(step) {
    const box = step.annotations.find((a) => a.kind === 'box');
    if (box && box.w && box.h) {
        const pad = 0.02;
        const left = Math.max(0, box.x - pad);
        const top = Math.max(0, box.y - pad);
        const width = Math.min(1, box.x + box.w + pad) - left;
        const height = Math.min(1, box.y + box.h + pad) - top;
        return width > 0 && height > 0 ? { left, top, width, height } : null;
    }
    const arrow = step.annotations.find((a) => a.kind === 'arrow');
    if (arrow) {
        const half = 0.06;
        const left = Math.max(0, arrow.x - half);
        const top = Math.max(0, arrow.y - half);
        const width = Math.min(1, arrow.x + half) - left;
        const height = Math.min(1, arrow.y + half) - top;
        return width > 0 && height > 0 ? { left, top, width, height } : null;
    }
    return null;
}
function pct(fraction) {
    return `${(fraction * 100).toFixed(2)}%`;
}
/**
 * Practice mode, inlined into the export.
 *
 * The reader rehearses the flow instead of scrolling it: one step at a time, and the way
 * forward is clicking the same control the guide points at. Two rules carried over from the
 * replay overlay: a step with no measured target gets a Continue button rather than an
 * invented click area, and a branching step never auto-advances — the choices are the only
 * way forward. State lives in classes on this page and nowhere else, the same zero-persistence
 * rule the variables panel follows.
 */
const PRACTICE_SCRIPT = `<script>
(function () {
  var toggle = document.getElementById('gt-practice-toggle');
  if (!toggle) return;
  var progress = document.getElementById('gt-practice-progress');
  var doneNote = document.getElementById('gt-practice-done');
  var steps = [].slice.call(document.querySelectorAll('ol.steps > li.step'));
  if (!steps.length) return;
  var on = false;
  var current = 0;

  function indexOfHash(hash) {
    for (var i = 0; i < steps.length; i++) if ('#' + steps[i].id === hash) return i;
    return -1;
  }
  function refresh() {
    for (var i = 0; i < steps.length; i++) steps[i].classList.toggle('is-current', on && i === current);
    if (progress) progress.textContent = 'Step ' + (current + 1) + ' of ' + steps.length;
    if (window.__gtDrawAnnotations) window.__gtDrawAnnotations();
  }
  function show(index) {
    current = index;
    if (doneNote) doneNote.hidden = true;
    var choice = document.querySelector('.branches.is-choice');
    if (choice) choice.classList.remove('is-choice');
    refresh();
    steps[index].scrollIntoView(true);
  }
  var quiz = document.getElementById('gt-quiz');
  var quizBody = document.getElementById('gt-quiz-body');
  var quizTitle = document.getElementById('gt-quiz-title');
  var asked = {};
  var correct = 0;
  var askedCount = 0;
  function assessments() {
    return Array.isArray(window.__gtAssessments) ? window.__gtAssessments : [];
  }
  function assessmentFor(chapter) {
    if (!chapter) return null;
    var list = assessments();
    for (var i = 0; i < list.length; i++) if (list[i] && list[i].chapter === chapter) return list[i];
    return null;
  }
  function lastOfChapter(index) {
    var ch = steps[index].getAttribute('data-chapter') || '';
    if (!ch) return false;
    if (index + 1 >= steps.length) return true;
    return (steps[index + 1].getAttribute('data-chapter') || '') !== ch;
  }
  function scoreNow() {
    window.__gtPracticeScore = askedCount ? Math.round((correct / askedCount) * 100) : 100;
    return window.__gtPracticeScore;
  }
  function finish() {
    var leftover = assessments().filter(function (one) { return one && one.chapter && !asked[one.chapter]; });
    if (leftover.length) return askQuiz(leftover[0], finish);
    if (doneNote) {
      doneNote.hidden = false;
      var score = scoreNow();
      if (askedCount) {
        doneNote.textContent = 'That was the last step — you scored ' + score + '% on the check (' + correct + ' of ' + askedCount + ').';
      }
      doneNote.scrollIntoView(false);
    }
    if (progress) progress.textContent = askedCount ? 'All steps followed · ' + scoreNow() + '%' : 'All ' + steps.length + ' steps followed';
  }
  function askQuiz(block, after) {
    if (!quiz || !quizBody || !block || !block.questions || !block.questions.length) return after();
    asked[block.chapter] = true;
    if (quizTitle) quizTitle.textContent = 'Check: ' + block.chapter;
    quizBody.innerHTML = '';
    var pending = block.questions.slice();
    function renderOne(q) {
      quizBody.innerHTML = '';
      var prompt = document.createElement('p');
      prompt.className = 'gt-quiz-prompt';
      prompt.textContent = q.prompt;
      quizBody.appendChild(prompt);
      var list = document.createElement('div');
      list.className = 'gt-quiz-choices';
      (q.choices || []).forEach(function (label, idx) {
        var btn = document.createElement('button');
        btn.type = 'button';
        btn.className = 'gt-quiz-choice';
        btn.textContent = label;
        btn.addEventListener('click', function () {
          askedCount += 1;
          if (idx === q.answer) {
            correct += 1;
            btn.classList.add('is-right');
          } else {
            btn.classList.add('is-wrong');
          }
          Array.prototype.forEach.call(list.querySelectorAll('button'), function (one) { one.disabled = true; });
          window.setTimeout(function () {
            if (pending.length) renderOne(pending.shift());
            else {
              quiz.hidden = true;
              after();
            }
          }, 450);
        });
        list.appendChild(btn);
      });
      quizBody.appendChild(list);
    }
    quiz.hidden = false;
    quiz.scrollIntoView(true);
    renderOne(pending.shift());
  }
  function complete(li) {
    var branches = li.querySelector('.branches');
    if (branches) {
      // A choice is never stepped over on the reader's behalf — same rule as the overlay.
      branches.classList.add('is-choice');
      var first = branches.querySelector('a');
      if (first) first.focus();
      return;
    }
    var advance = function () {
      if (current + 1 < steps.length) show(current + 1); else finish();
    };
    if (lastOfChapter(current)) {
      var block = assessmentFor(steps[current].getAttribute('data-chapter') || '');
      if (block && !asked[block.chapter]) return askQuiz(block, advance);
    }
    advance();
  }
  toggle.addEventListener('click', function () {
    on = !on;
    document.body.classList.toggle('gt-practice', on);
    toggle.setAttribute('aria-pressed', on ? 'true' : 'false');
    toggle.textContent = on ? 'Exit practice' : 'Practice this guide';
    if (progress) progress.hidden = !on;
    if (doneNote) doneNote.hidden = true;
    if (on) show(0); else refresh();
  });
  var hits = document.querySelectorAll('.gt-hit');
  for (var i = 0; i < hits.length; i++) {
    hits[i].addEventListener('click', function (event) {
      if (!on) return;
      event.stopPropagation();
      var li = event.currentTarget.closest('li.step');
      if (li !== steps[current]) return;
      complete(li);
    });
  }
  var shots = document.querySelectorAll('.gt-shot');
  for (var j = 0; j < shots.length; j++) {
    shots[j].addEventListener('click', function (event) {
      if (!on) return;
      var shot = event.currentTarget;
      var li = shot.closest('li.step');
      if (li !== steps[current]) return;
      if (!shot.querySelector('.gt-hit')) return;
      shot.classList.remove('gt-miss');
      void shot.offsetWidth;
      shot.classList.add('gt-miss');
      window.setTimeout(function () { shot.classList.remove('gt-miss'); }, 350);
    });
  }
  var continues = document.querySelectorAll('.practice-continue');
  for (var k = 0; k < continues.length; k++) {
    continues[k].addEventListener('click', function (event) {
      if (!on) return;
      var li = event.currentTarget.closest('li.step');
      if (li !== steps[current]) return;
      complete(li);
    });
  }
  var links = document.querySelectorAll('.branches a');
  for (var m = 0; m < links.length; m++) {
    links[m].addEventListener('click', function (event) {
      if (!on) return;
      var index = indexOfHash(event.currentTarget.getAttribute('href'));
      if (index < 0) return;
      event.preventDefault();
      show(index);
    });
  }
})();
</script>`;
function toSelfContainedHtml(guide, opts = {}) {
    const brand = guide.branding?.enabled ? guide.branding : null;
    const vars = guide.redaction.placeholders;
    const grouped = (0, schema_1.hasChapters)(guide.steps);
    const numberOf = new Map(guide.steps.map((step, i) => [step.id, i + 1]));
    const steps = guide.steps
        .map((step, index) => {
        const image = step.screenshot ? ScreenshotStore_1.screenshotStore.readDataUri(step.screenshot) : null;
        const target = image ? practiceTarget(step) : null;
        /**
         * The heading rides inside the <li> rather than breaking the list in two. An ordered list
         * split around a heading restarts its numbering, and the step numbers are the thing a
         * branch refers to — they have to stay continuous across chapters.
         */
        const heading = grouped && step.chapter?.trim() && guide.steps[index - 1]?.chapter?.trim() !== step.chapter.trim()
            ? `<h2 class="chapter">${escapeHtml(step.chapter.trim())}</h2>`
            : '';
        return `
      <li class="step" id="step-${escapeAttr(step.id)}" data-chapter="${escapeAttr(step.chapter?.trim() || '')}">
        ${heading}
        <h3><span class="step-num">${index + 1}</span>${withVariables(escapeHtml(step.title), vars)}</h3>
        ${step.body ? `<p>${withVariables(escapeHtml(step.body), vars)}</p>` : ''}
        ${step.why ? `<details class="why"><summary>Why this step exists</summary><p>${withVariables(escapeHtml(step.why), vars)}</p></details>` : ''}
        ${image
            ? `<span class="gt-shot"><img src="${image}" alt="${escapeAttr(step.title)}" loading="lazy" /><!--
             -->${(0, annotations_1.annotationOverlayMarkup)(step.annotations)}${target
                ? `<button type="button" class="gt-hit" style="left:${pct(target.left)};top:${pct(target.top)};width:${pct(target.width)};height:${pct(target.height)}" aria-label="Click the marked control to continue"></button>`
                : ''}</span>`
            : ''}
        ${step.verify ? `<p class="verify"><strong>Check:</strong> ${escapeHtml(describeVerify(step))}</p>` : ''}
        ${step.branches?.length
            ? `<div class="branches"><strong>What happens next depends on your answer:</strong><ul>${step.branches
                .map((b) => {
                const n = numberOf.get(b.goto);
                return `<li><a href="#step-${escapeAttr(b.goto)}">${escapeHtml(b.label)}</a>${n ? ` <span class="branch-to">→ step ${n}</span>` : ''}</li>`;
            })
                .join('')}</ul></div>`
            : ''}
        ${step.outputs?.length
            ? `<div class="outputs"><strong>This step produces a value you will need:</strong><ul>${step.outputs
                .map((o) => `<li>${escapeHtml(o.name)} → <code>${escapeHtml(o.target)}</code>${o.sensitive ? ' <em>(keep secret)</em>' : ''}</li>`)
                .join('')}</ul></div>`
            : ''}
        ${!target && !step.branches?.length
            ? `<button type="button" class="practice-continue">I did this — continue</button>`
            : ''}
      </li>`;
    })
        .join('\n');
    return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${escapeHtml(guide.title)}</title>
<style>
  /**
   * An exported guide is the *reader's* surface and wears the brand, in whichever value suits the
   * ground it lands on: --brand-onlight on a white page, --brand on a dark one (see
   * src/styles/00-tokens.css). They are not interchangeable — the bright value is a 2.4:1 link on
   * white.
   *
   * --on-accent is *computed*, not assumed. This block used to hand the step numeral #fff in both
   * themes while its own comment named 1.7:1 as the reason not to; inkOn() settles it, and settles
   * it for an arbitrary branding hex too. Branding replaces the accent in both themes, so its ink
   * is resolved once and inherited by the dark block.
   */
  :root { color-scheme: light dark; --fg: #0e141b; --muted: #4f5d6b; --bg: #ffffff; --card: #f1f5f9; --line: #d7e0e9;
          --accent: ${brand ? escapeAttr(brand.accent) : '#0b6e96'}; --on-accent: ${(0, customize_1.inkOn)(brand ? brand.accent : '#0b6e96')}; }
  @media (prefers-color-scheme: dark) {
    :root { --fg: #e6edf3; --muted: #93a1ae; --bg: #0b0e14; --card: #131a24; --line: #1e2733;${brand ? '' : ' --accent: #22b8d6; --on-accent: #0b0e14;'} }
  }
  * { box-sizing: border-box; }
  body { margin: 0; padding: 2.5rem 1.25rem 4rem; background: var(--bg); color: var(--fg);
         font: 16px/1.6 ${brand ? (0, customize_1.fontStack)(brand) : '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif'}; }
  .brand { display: flex; align-items: center; gap: .65rem; margin: 0 0 1.5rem; }
  .brand img { display: block; max-height: 2.25rem; max-width: 12rem; width: auto; height: auto; }
  .brand span { font-weight: 600; font-size: 1rem; letter-spacing: .01em; }
  main { max-width: 44rem; margin: 0 auto; }
  h1 { font-size: 1.9rem; line-height: 1.2; margin: 0 0 .5rem; }
  .intent { color: var(--muted); font-size: 1.05rem; margin: 0 0 1.5rem; }
  .meta { display: flex; flex-wrap: wrap; gap: .5rem; margin-bottom: 2rem; }
  .meta span { background: var(--card); border: 1px solid var(--line); border-radius: 999px; padding: .2rem .7rem; font-size: .82rem; color: var(--muted); }
  .prereq { background: var(--card); border: 1px solid var(--line); border-radius: 10px; padding: 1rem 1.25rem; margin-bottom: 2rem; }
  .prereq h2 { font-size: 1rem; margin: 0 0 .5rem; }
  ol.steps { list-style: none; margin: 0; padding: 0; }
  .step { border-top: 1px solid var(--line); padding: 1.75rem 0; }
  .step h3 { display: flex; align-items: baseline; gap: .6rem; font-size: 1.15rem; margin: 0 0 .6rem; }
  .step-num { flex: 0 0 auto; min-width: 1.6rem; height: 1.6rem; padding: 0 .35rem; border-radius: 4px;
              background: var(--accent); color: var(--on-accent); font-size: .85rem; font-weight: 700;
              font-variant-numeric: tabular-nums;
              display: inline-flex; align-items: center; justify-content: center; }
  .step p { margin: 0 0 .75rem; }
  .step img { display: block; max-width: 100%; height: auto; border: 1px solid var(--line); border-radius: 8px; }
  /**
   * inline-block so the wrapper shrink-wraps the picture. The practice hit area is positioned
   * in percentages of this wrapper; a block wrapper spans the column even when a cropped
   * screenshot is narrower, and every percentage would land beside the image.
   */
  .step .gt-shot { margin: .75rem 0; max-width: 100%; display: inline-block; }
  .why { margin: .5rem 0 .75rem; }
  .why summary { cursor: pointer; color: var(--accent); font-size: .9rem; }
  .verify { font-size: .9rem; color: var(--muted); }
  .chapter { font-size: 1.15rem; margin: 1.25rem 0 1.5rem; padding-bottom: .4rem; border-bottom: 2px solid var(--accent);
             letter-spacing: -.01em; }
  .step:first-child .chapter { margin-top: 0; }
  .branches { background: var(--card); border-left: 3px solid var(--accent); border-radius: 4px; padding: .75rem 1rem; font-size: .9rem; }
  .branches ul { margin: .4rem 0 0; padding-left: 1.1rem; }
  .branches a { color: var(--accent); }
  .branch-to { color: var(--muted); font-size: .85em; }
  .outputs { background: var(--card); border: 1px solid var(--line); border-radius: 8px; padding: .75rem 1rem; font-size: .9rem; }
  .outputs ul { margin: .4rem 0 0; padding-left: 1.1rem; }
  code { background: var(--card); border: 1px solid var(--line); border-radius: 4px; padding: .1rem .35rem; font-size: .88em; }
  .vars { background: var(--card); border: 1px solid var(--line); border-radius: 10px; padding: 1rem 1.25rem; margin-bottom: 2rem; }
  .vars h2 { font-size: 1rem; margin: 0 0 .3rem; }
  .vars .hint { color: var(--muted); font-size: .85rem; margin: 0 0 .8rem; }
  .vars .field { display: flex; align-items: center; gap: .6rem; margin-bottom: .5rem; flex-wrap: wrap; }
  .vars label { flex: 0 0 auto; font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
                font-size: .82rem; color: var(--muted); }
  .vars input { flex: 1 1 12rem; min-width: 0; font: inherit; font-size: .9rem; padding: .35rem .55rem;
                background: var(--bg); color: var(--fg); border: 1px solid var(--line); border-radius: 6px; }
  .vars input:focus-visible { outline: 2px solid var(--accent); outline-offset: 1px; }
  .gt-var { background: color-mix(in srgb, var(--accent) 16%, transparent); border-bottom: 1px solid var(--accent);
            border-radius: 3px; padding: 0 .18em; font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
            font-size: .92em; }
  .gt-var.is-filled { background: color-mix(in srgb, var(--accent) 9%, transparent); font-family: inherit; font-size: inherit; }
  .practice-bar { display: flex; align-items: center; gap: .75rem; margin: 0 0 1.75rem; }
  .practice-bar button { font: inherit; font-size: .9rem; font-weight: 600; padding: .45rem .95rem;
                         border: 1px solid var(--line); border-radius: 8px; background: var(--accent);
                         color: var(--on-accent); cursor: pointer; }
  .practice-bar button[aria-pressed="true"] { background: var(--card); color: var(--fg); }
  .practice-bar button:focus-visible { outline: 2px solid var(--accent); outline-offset: 2px; }
  .practice-progress { color: var(--muted); font-size: .9rem; }
  body.gt-practice .step { display: none; }
  body.gt-practice .step.is-current { display: block; }
  .gt-hit { display: none; position: absolute; margin: 0; padding: 0; background: transparent;
            border: 0; border-radius: 6px; cursor: pointer; }
  body.gt-practice .step.is-current .gt-hit { display: block; }
  .gt-hit:focus-visible { outline: 2px solid var(--accent); outline-offset: 2px; }
  .practice-continue { display: none; font: inherit; font-size: .9rem; font-weight: 600; margin-top: .75rem;
                       padding: .45rem .95rem; border: 1px solid var(--line); border-radius: 8px;
                       background: var(--card); color: var(--fg); cursor: pointer; }
  body.gt-practice .step.is-current .practice-continue { display: inline-block; }
  .practice-continue:focus-visible { outline: 2px solid var(--accent); outline-offset: 2px; }
  /* A miss states itself without motion too, so reduced-motion readers still get the signal. */
  .gt-shot.gt-miss img { outline: 3px solid color-mix(in srgb, var(--fg) 35%, transparent); }
  @media (prefers-reduced-motion: no-preference) {
    .gt-shot.gt-miss { animation: gt-shake .28s ease; }
  }
  @keyframes gt-shake { 25% { transform: translateX(-6px); } 75% { transform: translateX(6px); } }
  .branches.is-choice { outline: 2px solid var(--accent); outline-offset: 2px; }
  .practice-done { background: var(--card); border-left: 3px solid var(--accent); border-radius: 4px;
                   padding: .75rem 1rem; }
  .gt-quiz { background: var(--card); border: 1px solid var(--line); border-radius: 10px; padding: 1.1rem 1.25rem; margin: 1.5rem 0; }
  .gt-quiz h2 { font-size: 1.1rem; margin: 0 0 .75rem; }
  .gt-quiz-prompt { margin: 0 0 .75rem; font-weight: 600; }
  .gt-quiz-choices { display: flex; flex-direction: column; gap: .45rem; }
  .gt-quiz-choice { font: inherit; text-align: left; padding: .45rem .75rem; border: 1px solid var(--line);
                    border-radius: 8px; background: var(--bg); color: var(--fg); cursor: pointer; }
  .gt-quiz-choice:focus-visible { outline: 2px solid var(--accent); outline-offset: 1px; }
  .gt-quiz-choice.is-right { border-color: var(--accent); background: color-mix(in srgb, var(--accent) 14%, transparent); }
  .gt-quiz-choice.is-wrong { border-color: var(--fg); opacity: .75; }
  body.gt-practice .gt-quiz[hidden] { display: none !important; }
  @media print { .gt-quiz { display: none !important; } }
  footer { border-top: 1px solid var(--line); margin-top: 2.5rem; padding-top: 1.25rem; color: var(--muted); font-size: .85rem; }
  /**
   * The free-tier mark. Fixed rather than in flow so it survives a long guide without the reader
   * having to scroll to it, and pointer-events:none so it can never sit on top of a control. The
   * footer carries the same words in flow, which is what makes it print.
   */
  .gt-watermark {
    position: fixed; right: 14px; bottom: 12px; z-index: 40;
    padding: 5px 11px; border-radius: 999px;
    border: 1px solid var(--line); background: var(--card); color: var(--muted);
    font-size: .72rem; letter-spacing: .01em; pointer-events: none; opacity: .92;
  }
  .gt-watermark-line { font-weight: 600; }
  @media print { .gt-watermark { display: none; } }
${annotations_1.ANNOTATION_CSS}

  /**
   * Print rules, which the PDF export also renders through (pdfExport.ts). Three things
   * matter on paper that do not on screen:
   *
   *  1. Dark mode must not survive. A dark PDF is a full-bleed black rectangle — unreadable
   *     printed and hostile to ink. The variables are re-pinned to the light values rather
   *     than fighting prefers-color-scheme selector by selector.
   *  2. A <details> cannot be opened on paper. pdfExport.ts sets the open attribute on every
   *     one before printing — CSS cannot do it, and without that step the "why" silently
   *     vanishes from every printed guide. These rules only drop the disclosure triangle.
   *
   *  Note for future edits: this comment sits inside a template literal. No backticks.
   *  3. Steps should not straddle a page break, and a screenshot should never be orphaned
   *     from the instruction above it.
   */
  @media print {
    :root {
      color-scheme: light;
      --fg: #0e141b; --muted: #4f5d6b; --bg: #ffffff; --card: #f1f5f9; --line: #d7e0e9;
    }
    body { padding: 0; font-size: 11pt; }
    main { max-width: none; }
    .step { break-inside: avoid; page-break-inside: avoid; padding: 1.1rem 0; }
    .step h3 { break-after: avoid; page-break-after: avoid; }
    .step img { max-height: 12cm; object-fit: contain; }
    .why { break-inside: avoid; }
    .why[open] > summary, .why > summary { list-style: none; color: var(--muted); font-weight: 600; }
    .why > summary::-webkit-details-marker { display: none; }
    .brand { break-after: avoid; }
    footer { break-before: avoid; }
    a { text-decoration: none; color: inherit; }
    /* Practice chrome is a screen affordance; on paper every step prints, whatever mode the tab was in. */
    .practice-bar, .practice-continue, .gt-hit, .practice-done { display: none !important; }
    body.gt-practice .step { display: block; }
  }
</style>
</head>
<body>
<main>
  ${brand && (brand.logo || brand.organisation)
        ? `<header class="brand">${brand.logo ? `<img src="${escapeAttr(brand.logo)}" alt="${escapeAttr(brand.organisation || 'Logo')}" />` : ''}${brand.organisation ? `<span>${escapeHtml(brand.organisation)}</span>` : ''}</header>`
        : ''}
  <h1>${escapeHtml(guide.title)}</h1>
  ${guide.intent ? `<p class="intent">${escapeHtml(guide.intent)}</p>` : ''}
  <div class="meta">
    ${guide.estimatedMinutes ? `<span>about ${guide.estimatedMinutes} min</span>` : ''}
    ${guide.audience ? `<span>${escapeHtml(guide.audience)}</span>` : ''}
    <span>${guide.steps.length} steps</span>
  </div>
  <div class="practice-bar">
    <button type="button" id="gt-practice-toggle" aria-pressed="false">Practice this guide</button>
    <span class="practice-progress" id="gt-practice-progress" aria-live="polite" hidden></span>
  </div>
  ${guide.prerequisites.length
        ? `<section class="prereq"><h2>Before you start</h2><ul>${guide.prerequisites.map((p) => `<li>${escapeHtml(p)}</li>`).join('')}</ul></section>`
        : ''}
  ${vars.length
        ? `<section class="vars">
    <h2>Your values</h2>
    <p class="hint">Fill these in and they are substituted throughout the guide below. They stay in this page only — nothing is saved, sent, or remembered once you close the tab.</p>
    ${vars
            .map((name, i) => `<div class="field"><label for="gt-var-${i}">${escapeHtml(name)}</label><input id="gt-var-${i}" type="text" data-fills="${escapeAttr(name)}" placeholder="paste yours here" autocomplete="off" spellcheck="false" /></div>`)
            .join('')}
  </section>`
        : ''}
  <ol class="steps">${steps}</ol>
  ${guide.assessments?.length
        ? `<script>window.__gtAssessments=${JSON.stringify(guide.assessments)};</script>`
        : ''}
  <section class="gt-quiz" id="gt-quiz" hidden>
    <h2 id="gt-quiz-title">Check your understanding</h2>
    <div id="gt-quiz-body"></div>
  </section>
  <p class="practice-done" id="gt-practice-done" hidden>That was the last step — you have followed the whole guide.</p>
  ${opts.watermark ? `<div class="gt-watermark" aria-hidden="true">${escapeHtml(opts.watermark)}</div>` : ''}
  <footer>
    ${opts.watermark ? `<p class="gt-watermark-line">${escapeHtml(opts.watermark)}</p>` : ''}
    <p>${brand?.showAttribution === false ? 'Generated on' : 'Generated by 1ShowcaseTool on'} ${escapeHtml(formatDate(guide.generatedAt))}.</p>
    ${guide.redaction.rules.length ? `<p>Redaction applied: ${escapeHtml(guide.redaction.rules.join(', '))}.</p>` : ''}
    ${guide.redaction.placeholders.length
        /**
         * A record, not an instruction. The "Your values" panel above is what tells the reader
         * to substitute; this line exists so a teammate auditing the guide can see which names
         * were minted by the redaction pass. One element, one job.
         */
        ? `<p>Placeholders minted by the redaction pass: ${guide.redaction.placeholders.map((p) => `<code>${escapeHtml(p)}</code>`).join(', ')}.</p>`
        : ''}
  </footer>
</main>
${annotations_1.ANNOTATION_SCRIPT}
${vars.length ? VARIABLES_SCRIPT : ''}
${PRACTICE_SCRIPT}
</body>
</html>`;
}
/**
 * Wrap every placeholder occurrence so the reader can fill it in (docs/competitor-features.md
 * §2.9). Supademo calls these dynamic variables and resolves them on their server per viewer;
 * ours resolve in the reader's own browser, in a file with no network access.
 *
 * Runs on text that has **already been escaped**, so it looks for the escaped form —
 * `<YOUR_CLIENT_ID>` reaches here as `&lt;YOUR_CLIENT_ID&gt;`. Doing it before escaping would
 * mean emitting markup and then escaping our own tags.
 */
function withVariables(escaped, placeholders) {
    let out = escaped;
    for (const placeholder of placeholders) {
        const needle = escapeHtml(placeholder);
        if (!needle || !out.includes(needle))
            continue;
        out = out
            .split(needle)
            .join(`<span class="gt-var" data-var="${escapeAttr(placeholder)}">${needle}</span>`);
    }
    return out;
}
function describeVerify(step) {
    if (!step.verify)
        return '';
    switch (step.verify.kind) {
        case 'urlMatches':
            return `the page URL now contains ${step.verify.value}`;
        case 'selectorPresent':
            return `the expected element appears on the page`;
        case 'selectorAbsent':
            return `the element you just used is gone`;
        case 'textPresent':
            return `the page shows "${step.verify.value}"`;
        case 'manual':
            return step.verify.value || 'confirm this yourself before continuing';
    }
}
function formatDate(iso) {
    const date = new Date(iso);
    return Number.isNaN(date.getTime()) ? iso : date.toISOString().slice(0, 10);
}
function escapeHtml(value) {
    return value.replace(/[&<>"']/g, (ch) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[ch]);
}
function escapeAttr(value) {
    return escapeHtml(value);
}
function escapeAlt(value) {
    return value.replace(/[[\]]/g, '');
}
/** Screenshots are stored as "<sessionId>/<file>.png"; exports flatten that. */
function basename(storePath) {
    const parts = storePath.split('/');
    return parts[parts.length - 1];
}
/**
 * A collection index (docs/competitor-features.md §2.6).
 *
 * Written beside one self-contained HTML file per guide, so a collection on disk is a folder
 * you can zip, email or commit — the same honest no-cloud path a single guide already takes.
 * The index links relatively; nothing here reaches the network.
 */
function toCollectionIndexHtml(collection, entries, opts = {}) {
    const brand = entries.find((e) => e.guide.branding?.enabled)?.guide.branding ?? null;
    const totalSteps = entries.reduce((sum, e) => sum + e.guide.steps.length, 0);
    return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${escapeHtml(collection.title)}</title>
<style>
  :root { color-scheme: light dark; --fg: #0e141b; --muted: #4f5d6b; --bg: #ffffff; --card: #f1f5f9; --line: #d7e0e9;
          --accent: ${brand ? escapeAttr(brand.accent) : '#0b6e96'}; --on-accent: ${(0, customize_1.inkOn)(brand ? brand.accent : '#0b6e96')}; }
  @media (prefers-color-scheme: dark) {
    :root { --fg: #e6edf3; --muted: #93a1ae; --bg: #0b0e14; --card: #131a24; --line: #1e2733;${brand ? '' : ' --accent: #22b8d6; --on-accent: #0b0e14;'} }
  }
  * { box-sizing: border-box; }
  body { margin: 0; padding: 2.5rem 1.25rem 4rem; background: var(--bg); color: var(--fg);
         font: 16px/1.6 ${brand ? (0, customize_1.fontStack)(brand) : '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif'}; }
  main { max-width: 44rem; margin: 0 auto; }
  .brand { display: flex; align-items: center; gap: .65rem; margin: 0 0 1.5rem; }
  .brand img { display: block; max-height: 2.25rem; max-width: 12rem; width: auto; height: auto; }
  h1 { font-size: 1.9rem; line-height: 1.2; margin: 0 0 .5rem; }
  .intent { color: var(--muted); font-size: 1.05rem; margin: 0 0 1.5rem; }
  .meta { color: var(--muted); font-size: .85rem; margin: 0 0 2rem; }
  ol { list-style: none; margin: 0; padding: 0; counter-reset: g; }
  li { counter-increment: g; border-top: 1px solid var(--line); }
  a { display: flex; gap: .8rem; align-items: baseline; padding: 1rem .25rem; color: inherit; text-decoration: none; }
  a:hover { background: var(--card); }
  a:focus-visible { outline: 2px solid var(--accent); outline-offset: -2px; }
  .n { flex: 0 0 auto; min-width: 1.6rem; height: 1.6rem; padding: 0 .35rem; border-radius: 4px;
       background: var(--accent); color: var(--on-accent); font-size: .85rem; font-weight: 700;
       font-variant-numeric: tabular-nums;
       display: inline-flex; align-items: center; justify-content: center; }
  .t { flex: 1 1 auto; font-weight: 600; }
  .s { flex: 0 0 auto; color: var(--muted); font-size: .85rem; }
  footer { border-top: 1px solid var(--line); margin-top: 2.5rem; padding-top: 1.25rem; color: var(--muted); font-size: .85rem; }
</style>
</head>
<body>
<main>
  ${brand && (brand.logo || brand.organisation)
        ? `<header class="brand">${brand.logo ? `<img src="${escapeAttr(brand.logo)}" alt="${escapeAttr(brand.organisation || 'Logo')}" />` : ''}${brand.organisation ? `<span>${escapeHtml(brand.organisation)}</span>` : ''}</header>`
        : ''}
  <h1>${escapeHtml(collection.title)}</h1>
  ${collection.intent ? `<p class="intent">${escapeHtml(collection.intent)}</p>` : ''}
  <p class="meta">${entries.length} guide${entries.length === 1 ? '' : 's'} · ${totalSteps} steps in total</p>
  <ol>
    ${entries
        .map((entry, i) => `<li><a href="${escapeAttr(entry.file)}">
      <span class="n">${i + 1}</span>
      <span class="t">${escapeHtml(entry.guide.title)}</span>
      <span class="s">${entry.guide.steps.length} steps</span>
    </a></li>`)
        .join('\n    ')}
  </ol>
  <footer>
    ${opts.watermark ? `<p class="gt-watermark-line">${escapeHtml(opts.watermark)}</p>` : ''}
    <p>${brand?.showAttribution === false ? 'Generated on' : 'Generated by 1ShowcaseTool on'} ${escapeHtml(formatDate(new Date().toISOString()))}. Every guide here is a self-contained file — this folder works offline.</p>
  </footer>
</main>
</body>
</html>`;
}
//# sourceMappingURL=exporters.js.map